[package]
name = "autozig-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
autozig-ecs = { path = "../../autozig-ecs" }
rand = "0.8"

[[bin]]
name = "bench_autozig"
path = "src/bench_autozig.rs"

[[bin]]
name = "bench_autozig_raw"
path = "src/bench_autozig_raw.rs"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
