[package]
name = "autozig-image"
version = "0.1.0"
edition = "2021"

[dependencies]
autozig = { path = "../../autozig", version = "0.1.2" }
autozig-asset = { path = "../autozig-asset" }
autozig-color = { path = "../autozig-color" }

[build-dependencies]
autozig-build = { path = "../../autozig/gen/build", version = "0.1.2" }