[package]
name = "autozig-asset"
version = "0.1.0"
edition = "2021"

[dependencies]
autozig = { path = "../../autozig", version = "0.1.2" }
# autozig-utils = { path = "../autozig-utils" }  # 暂时注释，依赖库有编译问题

[dev-dependencies]
tempfile = "3.8"

[build-dependencies]
autozig-build = { path = "../../autozig/gen/build", version = "0.1.2" }