/* Auto-generated by AutoZig - Do not edit */
/* eslint-disable */

export interface WasmExports {
  get_version(): number;
  run_all_demos(): number;
  demo_run_app(): number;
  demo_run_ecs(): number;
  demo_run_math(): number;
  demo_math_vec3_new(x: number, y: number, z: number): number;
  demo_math_vec3_length(x: number, y: number, z: number): number;
  demo_math_quat_identity(): number;
  demo_run_state(): number;
  demo_run_time_task(): number;
  demo_time_stopwatch_new(): number;
  demo_time_timer_once(duration_secs: number): number;
  demo_time_timer_repeating(duration_secs: number): number;
  demo_run_json(): number;
  demo_json_parse_number(value: number): number;
  demo_json_parse_object(): number;
  demo_json_parse_array(): number;
  get_info_string_len(): bigint;
  get_pointer_size(): bigint;
  run_memory_test(): number;
}

export interface AutoZigWasm {
  exports: WasmExports;
  memory: WebAssembly.Memory;
  instance: WebAssembly.Instance;
}

/** Load WASM module from URL */
export function loadWasm(path: string): Promise<AutoZigWasm>;

/** Load WASM module from ArrayBuffer */
export function loadWasmSync(buffer: ArrayBuffer): Promise<AutoZigWasm>;
