/* Auto-generated by AutoZig - Do not edit */
/* eslint-disable */

export interface WasmExports {
  run_hello_world(): void;
  get_system_count(): number;
  run_multiple_times(times: number): void;
}

export interface AutoZigWasm {
  exports: WasmExports;
  memory: WebAssembly.Memory;
  instance: WebAssembly.Instance;
}

/** Load WASM module from URL */
export function loadWasm(path: string): Promise<AutoZigWasm>;

/** Load WASM module from ArrayBuffer */
export function loadWasmSync(buffer: ArrayBuffer): Promise<AutoZigWasm>;
