[package]
name = "autozig-winit"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
autozig = { path = "../../autozig" }
autozig-window = { path = "../autozig-window" }
autozig-app = { path = "../autozig-app" }
winit = "0.29"
raw-window-handle = "0.6"

[build-dependencies]
autozig-build = { path = "../../autozig/gen/build" }

[lib]
crate-type = ["lib"]